#pragma once

namespace data {
constexpr auto day01 = "1000\n\n2000\n3000\n\n4000\n\n5000\n6000\n\n7000\n8000\n9000\n\n"
                       "10000\n\n";
constexpr auto day02 = "A Y\nB X\nC Z\n";
constexpr auto day03 = "vJrwpWtwJgWrhcsFMMfFFhFp\n"
                       "jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL\n"
                       "PmmdzqPrVvPwwTWBwg\n"
                       "wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn\n"
                       "ttgJtRGJQctTZtZT\n"
                       "CrZsJsPPZsGzwwsLwLmpwMDw\n";
constexpr auto day04 = "2-4,6-8\n"
                       "2-3,4-5\n"
                       "5-7,7-9\n"
                       "2-8,3-7\n"
                       "6-6,4-6\n"
                       "2-6,4-8\n";
constexpr auto day05 = "    [D]    \n"
                       "[N] [C]    \n"
                       "[Z] [M] [P]\n"
                       " 1   2   3 \n"
                       "\n"
                       "move 1 from 2 to 1\n"
                       "move 3 from 1 to 3\n"
                       "move 2 from 2 to 1\n"
                       "move 1 from 1 to 2\n";
constexpr auto day07 = "$ cd /\n"
                       "$ ls\n"
                       "dir a\n"
                       "14848514 b.txt\n"
                       "8504156 c.dat\n"
                       "dir d\n"
                       "$ cd a\n"
                       "$ ls\n"
                       "dir e\n"
                       "29116 f\n"
                       "2557 g\n"
                       "62596 h.lst\n"
                       "$ cd e\n"
                       "$ ls\n"
                       "584 i\n"
                       "$ cd ..\n"
                       "$ cd ..\n"
                       "$ cd d\n"
                       "$ ls\n"
                       "4060174 j\n"
                       "8033020 d.log\n"
                       "5626152 d.ext\n"
                       "7214296 k\n";
constexpr auto day08 = "30373\n"
                       "25512\n"
                       "65332\n"
                       "33549\n"
                       "35390\n";
constexpr auto day10 = "addx 15\n"
                       "addx -11\n"
                       "addx 6\n"
                       "addx -3\n"
                       "addx 5\n"
                       "addx -1\n"
                       "addx -8\n"
                       "addx 13\n"
                       "addx 4\n"
                       "noop\n"
                       "addx -1\n"
                       "addx 5\n"
                       "addx -1\n"
                       "addx 5\n"
                       "addx -1\n"
                       "addx 5\n"
                       "addx -1\n"
                       "addx 5\n"
                       "addx -1\n"
                       "addx -35\n"
                       "addx 1\n"
                       "addx 24\n"
                       "addx -19\n"
                       "addx 1\n"
                       "addx 16\n"
                       "addx -11\n"
                       "noop\n"
                       "noop\n"
                       "addx 21\n"
                       "addx -15\n"
                       "noop\n"
                       "noop\n"
                       "addx -3\n"
                       "addx 9\n"
                       "addx 1\n"
                       "addx -3\n"
                       "addx 8\n"
                       "addx 1\n"
                       "addx 5\n"
                       "noop\n"
                       "noop\n"
                       "noop\n"
                       "noop\n"
                       "noop\n"
                       "addx -36\n"
                       "noop\n"
                       "addx 1\n"
                       "addx 7\n"
                       "noop\n"
                       "noop\n"
                       "noop\n"
                       "addx 2\n"
                       "addx 6\n"
                       "noop\n"
                       "noop\n"
                       "noop\n"
                       "noop\n"
                       "noop\n"
                       "addx 1\n"
                       "noop\n"
                       "noop\n"
                       "addx 7\n"
                       "addx 1\n"
                       "noop\n"
                       "addx -13\n"
                       "addx 13\n"
                       "addx 7\n"
                       "noop\n"
                       "addx 1\n"
                       "addx -33\n"
                       "noop\n"
                       "noop\n"
                       "noop\n"
                       "addx 2\n"
                       "noop\n"
                       "noop\n"
                       "noop\n"
                       "addx 8\n"
                       "noop\n"
                       "addx -1\n"
                       "addx 2\n"
                       "addx 1\n"
                       "noop\n"
                       "addx 17\n"
                       "addx -9\n"
                       "addx 1\n"
                       "addx 1\n"
                       "addx -3\n"
                       "addx 11\n"
                       "noop\n"
                       "noop\n"
                       "addx 1\n"
                       "noop\n"
                       "addx 1\n"
                       "noop\n"
                       "noop\n"
                       "addx -13\n"
                       "addx -19\n"
                       "addx 1\n"
                       "addx 3\n"
                       "addx 26\n"
                       "addx -30\n"
                       "addx 12\n"
                       "addx -1\n"
                       "addx 3\n"
                       "addx 1\n"
                       "noop\n"
                       "noop\n"
                       "noop\n"
                       "addx -9\n"
                       "addx 18\n"
                       "addx 1\n"
                       "addx 2\n"
                       "noop\n"
                       "noop\n"
                       "addx 9\n"
                       "noop\n"
                       "noop\n"
                       "noop\n"
                       "addx -1\n"
                       "addx 2\n"
                       "addx -37\n"
                       "addx 1\n"
                       "addx 3\n"
                       "noop\n"
                       "addx 15\n"
                       "addx -21\n"
                       "addx 22\n"
                       "addx -6\n"
                       "addx 1\n"
                       "noop\n"
                       "addx 2\n"
                       "addx 1\n"
                       "noop\n"
                       "addx -10\n"
                       "noop\n"
                       "noop\n"
                       "addx 20\n"
                       "addx 1\n"
                       "addx 2\n"
                       "addx 2\n"
                       "addx -6\n"
                       "addx -11\n"
                       "noop\n"
                       "noop\n"
                       "noop\n";
constexpr auto day11 = "Monkey 0:\n"
                       "  Starting items: 79, 98\n"
                       "  Operation: new = old * 19\n"
                       "  Test: divisible by 23\n"
                       "    If true: throw to monkey 2\n"
                       "    If false: throw to monkey 3\n"
                       "\n"
                       "Monkey 1:\n"
                       "  Starting items: 54, 65, 75, 74\n"
                       "  Operation: new = old + 6\n"
                       "  Test: divisible by 19\n"
                       "    If true: throw to monkey 2\n"
                       "    If false: throw to monkey 0\n"
                       "\n"
                       "Monkey 2:\n"
                       "  Starting items: 79, 60, 97\n"
                       "  Operation: new = old * old\n"
                       "  Test: divisible by 13\n"
                       "    If true: throw to monkey 1\n"
                       "    If false: throw to monkey 3\n"
                       "\n"
                       "Monkey 3:\n"
                       "  Starting items: 74\n"
                       "  Operation: new = old + 3\n"
                       "  Test: divisible by 17\n"
                       "    If true: throw to monkey 0\n"
                       "    If false: throw to monkey 1\n";
constexpr auto day12 = "Sabqponm\n"
                       "abcryxxl\n"
                       "accszExk\n"
                       "acctuvwj\n"
                       "abdefghi\n";

constexpr auto day13 = "[1,1,3,1,1]\n"
                       "[1,1,5,1,1]\n"
                       "\n"
                       "[[1],[2,3,4]]\n"
                       "[[1],4]\n"
                       "\n"
                       "[9]\n"
                       "[[8,7,6]]\n"
                       "\n"
                       "[[4,4],4,4]\n"
                       "[[4,4],4,4,4]\n"
                       "\n"
                       "[7,7,7,7]\n"
                       "[7,7,7]\n"
                       "\n"
                       "[]\n"
                       "[3]\n"
                       "\n"
                       "[[[]]]\n"
                       "[[]]\n"
                       "\n"
                       "[1,[2,[3,[4,[5,6,7]]]],8,9]\n"
                       "[1,[2,[3,[4,[5,6,0]]]],8,9]\n";
constexpr auto day14 = "498,4 -> 498,6 -> 496,6\n"
                       "503,4 -> 502,4 -> 502,9 -> 494,9\n";
constexpr auto day15 = "Sensor at x=2, y=18: closest beacon is at x=-2, y=15\n"
                       "Sensor at x=9, y=16: closest beacon is at x=10, y=16\n"
                       "Sensor at x=13, y=2: closest beacon is at x=15, y=3\n"
                       "Sensor at x=12, y=14: closest beacon is at x=10, y=16\n"
                       "Sensor at x=10, y=20: closest beacon is at x=10, y=16\n"
                       "Sensor at x=14, y=17: closest beacon is at x=10, y=16\n"
                       "Sensor at x=8, y=7: closest beacon is at x=2, y=10\n"
                       "Sensor at x=2, y=0: closest beacon is at x=2, y=10\n"
                       "Sensor at x=0, y=11: closest beacon is at x=2, y=10\n"
                       "Sensor at x=20, y=14: closest beacon is at x=25, y=17\n"
                       "Sensor at x=17, y=20: closest beacon is at x=21, y=22\n"
                       "Sensor at x=16, y=7: closest beacon is at x=15, y=3\n"
                       "Sensor at x=14, y=3: closest beacon is at x=15, y=3\n"
                       "Sensor at x=20, y=1: closest beacon is at x=15, y=3\n";
constexpr auto day16 = "Valve AA has flow rate=0; tunnels lead to valves DD, II, BB\n"
                       "Valve BB has flow rate=13; tunnels lead to valves CC, AA\n"
                       "Valve CC has flow rate=2; tunnels lead to valves DD, BB\n"
                       "Valve DD has flow rate=20; tunnels lead to valves CC, AA, EE\n"
                       "Valve EE has flow rate=3; tunnels lead to valves FF, DD\n"
                       "Valve FF has flow rate=0; tunnels lead to valves EE, GG\n"
                       "Valve GG has flow rate=0; tunnels lead to valves FF, HH\n"
                       "Valve HH has flow rate=22; tunnel leads to valve GG\n"
                       "Valve II has flow rate=0; tunnels lead to valves AA, JJ\n"
                       "Valve JJ has flow rate=21; tunnel leads to valve II\n";
constexpr auto day17 = ">>><<><>><<<>><>>><<<>>><<<><<<>><>><<>>\n";
} // namespace data
